### ISSUE TITLE
how do i set it up in my modpack its not working[Issue]

### ISSUE THREAD

**Issue by Thunderrock424242** [nanite/Default-Server-Properties#2]
### Minecraft Version

1.20.1

### Modloader

forge 47.2.0

### Mod version

idk

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

idk

### Description of the issue you are having

i need help setting up my mod idk how to do it i looked at the mod home page and idk how

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Just add a `default-server.properties` to your root game folder / modpack 

Example:

```
hardcore=true
hide-online-players=true
level-name=hello
level-seed=4832758927459874
level-type=default
max-players=15
motd=fuckgaz
network-compression-threshold=156
online-mode=false
```

This will now be merged with a fresh server properties :D

**Comment by Thunderrock424242** [comment]
> Just add a `default-server.properties` to your root game folder / modpack 
> 
> 
> 
> Example:
> 
> 
> 
> ```
> 
> hardcore=true
> 
> hide-online-players=true
> 
> level-name=hello
> 
> level-seed=4832758927459874
> 
> level-type=default
> 
> max-players=15
> 
> motd=fuckgaz
> 
> network-compression-threshold=156
> 
> online-mode=false
> 
> ```
> 
> 
> 
> This will now be merged with a fresh server properties :D

So like modpack name/ local and I would put it there or in the modpack name/ file here?
